when:
  - event: push
    branch: ci

steps:
  - name: test
    image: marcaureln/volta:latest
    commands:
      - volta install node@24 pnpm@10
      - pnpm i
      - pnpm exec playwright install
      - pnpm test
      - pnpm build
